
TYPE
	RdBuffer_typ : 	STRUCT 
		rdFloat1 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat2 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat3 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat4 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat5 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat6 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdFloat7 : ARRAY[0..MAX_FLOAT_NUM]OF REAL;
		rdInt1 : ARRAY[0..MAX_INT_NUM]OF DINT;
		rdInt2 : ARRAY[0..MAX_INT_NUM]OF DINT;
		rdInt3 : ARRAY[0..MAX_INT_NUM]OF DINT;
		rdInt4 : ARRAY[0..MAX_INT_NUM]OF DINT;
	END_STRUCT;
END_TYPE
